
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
    volumes:
      - mysql-db:/var/lib/mysql
    healthcheck:
      test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\" || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  api:
    build: .
    environment:
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      MAILCHIMP_TRANSACTIONAL_API_KEY: ${MAILCHIMP_TRANSACTIONAL_API_KEY}
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/src/migrations 
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /src/app
          
        - action: rebuild
          path: requirements.txt
          target: /src/requirements.txt

volumes:
        mysql-db: